eprbell/dali-rp2

src/dali/abstract_input_plugin.py, src/dali/dali_main.py, src/dali/plugin/input/rest/coinbase.py, src/dali/plugin/input/rest/coinbase_pro.py
added caching and parallel API calls mainly to help speed up development
=> download data from coinbase in parallel & caching

src/dali/plugin/input/csv/blockfi.py
Adding support for additional blockfi transaction types in my csv export
=> Support additional blockfi transactions

src/dali/out_transaction.py
Discussion on the related PR makes sense. Capturing the discussion in code for the future reader and closing this out.
Fixes #75
=> Comment about why out transaction fee is required

src/dali/plugin/pair_converter/ccxt.py, src/dali/plugin/pair_converter/csv/kraken.py, tests/test_plugin_ccxt.py
This fixes some alternative market handling in the CCXT pair converter as well as allow the pair converter to continue with REST price resolution if the file isn't found on Google Drive like what is described in #112 
EDIT: Let me do a full pull and double-check if all alternative markets are added. That could be ~12 hours.
=> Improve File Handling in Kraken CSV

src/dali/plugin/input/rest/coinbase.py
=> Handle detection of None in the to field of the transaction for coinbase plugin as a part of filtering

docs/configuration_file.md
This looked like a copy/paste error.
=> Documentation updates

input/test_ods_rp2_input.ini, src/dali/configuration.py, src/dali/plugin/input/csv/bitbank_supplemental.py, src/dali/plugin/input/csv/ledger.py, src/dali/plugin/input/csv/trezor.py, src/dali/plugin/input/csv/trezor_old.py, src/dali/plugin/input/csv/trezor_v2.py, src/dali/plugin/input/ods/rp2_input.py, src/dali/plugin/input/rest/binance_com.py, src/dali/plugin/input/rest/bitbank.py, src/dali/plugin/input/rest/coinbase.py, src/dali/plugin/input/rest/coinbase_pro.py, tests/test_plugin_binance_com.py, tests/test_plugin_ods_rp2_input.py
This is just an isort run to clean up code according to the new rules.
=> Sort code with Isort

src/dali/abstract_transaction.py
`dali` currently invokes `inspect.signature()` on every transaction initialization, which is the majority of the runtime after including https://github.com/eprbell/dali-rp2/pull/151. We start with a runtime of:
```
%timeit InTransaction('test', 'a', 'b', '2023-03-30 00:00:00Z', 'c', 'd', 'e', 'BUY', '1', '1')
97.2 µs ± 4.3 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
And by adding a class-level cache, we cut the runtime by ~2/3:
```
%timeit InTransaction('test', 'a', 'b', '2023-03-30 00:00:00Z', 'c', 'd', 'e', 'BUY', '1', '1')
35.1 µs ± 465 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
=> Cache signature parameters during transaction initialization

src/dali/plugin/input/rest/bitbank.py
As per discussion [here](https://github.com/eprbell/dali-rp2/issues/154)
This passed all local tests btw.
=> Appending "/fee" to bitbank maker fee INCOME transactions

src/dali/plugin/input/rest/kraken.py, src/dali/plugin/pair_converter/csv/kraken.py, src/stubs/ccxt.pyi, tests/test_plugin_kraken.py
Seems like a lot. Is this normal? I've never used black before, and was just following the unit tests on the dev README (in order) and it kept resulting in these changes, so thought I'd commit them. 
If these aren't desired changes, should I try to learn about black and make any necessary changes to the config of how that is working? Any help in the right direction appreciated!
=> Automated reformat from black resulted in this

src/dali/plugin/pair_converter/ccxt.py, src/stubs/ccxt.pyi
As per [Issue 159](https://github.com/eprbell/dali-rp2/issues/159#issuecomment-1553862095)
@macanudo527 Seems to have worked. Is this the intended way of doing this though?
=> Adding upbit exchange via ccxt

src/dali/dali_main.py
As per [Issue 182](https://github.com/eprbell/dali-rp2/issues/182)
=> Removed redundant NativeFiat check

src/dali/plugin/input/rest/binance_com.py
=> binance dividends

setup.cfg, src/dali/plugin/country/es.py
Here again.
i´m doing separate PR to this and Binance dividends
=> spanish support

.github/workflows/unix_unit_tests.yml, .github/workflows/windows_unit_tests.yml, README.dev.md, README.md, setup.cfg
This is to bump the minimum version of Python from 3.7 to 3.8
=> Bump Python version to 3.8

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/etc.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
I just found these extremely useful in the other projects I've been working on, so I modified a few so they apply to our project and help keep things sorted and moving forward.
I'm open to suggestions if you think something is missing or if they are too much.
=> Add Github Templates

src/dali/ccxt_pagination.py
This is just some housekeeping. I should have abstracted the pagination more when I submitted the id pagination PR. Also, the templates seem to have a few extra whitespaces.
No additional testing should be needed.
Technical Changes
The title of the pull request will be included in the release notes.
=> Add page based pagination

README.md
Output file is .ini, not .config.
=> Update README.md: Output file is .ini, not .config.

README.dev.md, README.md
For Windows 10, Microsoft Visual C++ 14.0 or greater is needed for multidict.  Account for running scripts being disabled.
For Other Unix-like Systems, made formatting consistent with other sections.
=> Update README*.md: Windows 10 and Other Unix-like Systems

docs/configuration_file.md
Reference [OUT-Transaction Table Format in ](https://github.com/eprbell/rp2/blob/main/docs/input_files.md#out-transaction-table-format)
> transaction_type: DONATE, FEE, GIFT or SELL.
=> Update configuration_file.md: Out transaction_type includes Fee
